<div class="jumbotron">
    <h1>Workflow Configurator</h1>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel-group" id="wf-accordion">
            <?php foreach($this->workflowList as $workflow): ?>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4 class="panel-title pointer" data-toggle="collapse" data-parent="#wf-accordion" data-target="#collapse-<?php echo $this->escapeHtmlAttr($workflow->getId()) ?>">
                        <?php echo $this->escapeHtml($workflow->getName()) ?>                        
                    </h4>
                </div>
                <div id="collapse-<?php echo $this->escapeHtmlAttr($workflow->getId()) ?>" class="panel-collapse collapse">
                    <div class="panel-body">
                        <p><?php echo $this->escapeHtml($workflow->getDescription()) ?></p>
                        <p></p>
                        <p>
                            <a href="<?php echo $this->url('workflow_configurator_start', array('id' => $workflow->getId())) ?>" class="btn btn-primary"><span class="glyphicon glyphicon-wrench"></span>&nbsp;<?php echo $this->translate('configure') ?></a>
                            <a href="#" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span>&nbsp;<?php echo $this->translate('edit') ?></a>
                            <a href="#" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span>&nbsp;<?php echo $this->translate('delete') ?></a>
                        </p>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p></p>
        <a href="#" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span>&nbsp;<?php echo $this->translate('add Workflow') ?></a>
    </div>
</div>