<?php

namespace Ginger\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-09 at 17:32:34.
 */
class BootstrapTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Ginger\Core\Bootstrap::init
     */
    public function testInit()
    {
        //Ginger\Core\Bootstrap is also used to bootstrap unit tests
        //so we only need to check that zf2 ServiceManager is available
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', \Ginger\Core\Bootstrap::getServiceManager());
    }
}
