<?php
namespace WfConfigBackend\Facade;

use Ginger\Test\TestCase;
use WfConfigBackend\Model\Workflow\WorkflowRepository;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-30 at 21:31:33.
 */
class WorkflowFacadeTest extends TestCase
{
    /**
     * @var WorkflowFacade
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $workflowRepository = new WorkflowRepository($this->getCrudAdapter());
        
        $this->object = new WorkflowFacade();
        
        $this->object->setWorkflowRepository($workflowRepository);
    }

    /**
     * @covers WfConfigBackend\Facade\WorkflowFacade::create
     */
    public function testCreate()
    {
        $workflow = new WorkflowDto();
        $workflow->setName('TestWorkflow')
            ->setDescription('A test workflow');
        
        $this->object->create($workflow);
        
        $this->assertEquals('1', $workflow->getId());
    }
    
    public function testGet()
    {
        $workflow = new WorkflowDto();
        $workflow->setName('TestWorkflow')
            ->setDescription('A test workflow');
        
        $this->object->create($workflow);
        
        $checkWorkflow = $this->object->get($workflow->getId());
        
        $this->assertEquals($workflow->getArrayCopy(), $checkWorkflow->getArrayCopy());
    }
    
    public function testListAll()
    {
        $workflow = new WorkflowDto();
        $workflow->setName('TestWorkflow')
            ->setDescription('A test workflow');
        
        $this->object->create($workflow);
        
        $workflow = new WorkflowDto();
        $workflow->setName('TestWorkflow2')
            ->setDescription('Another test workflow');
        
        $this->object->create($workflow);
        
        $list = $this->object->listAll();
        
        $this->assertEquals(2, count($list));
        $this->assertEquals('TestWorkflow2', $list[1]->getName());
    }
}
