<?php
namespace Ginger\Core\Repository\Resource;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-13 at 21:27:25.
 */
class ResourceTypeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Ginger\Core\Repository\Resource\ResourceType::__construct
     * @covers Ginger\Core\Repository\Resource\ResourceType::getValue
     */
    public function test__constructAndGetValue()
    {
        $resourceType = new ResourceType('workflow');
        
        $this->assertEquals('workflow', $resourceType->getValue());
    }
    
    /**
     * @covers Ginger\Core\Repository\Resource\ResourceType::__construct
     * @expectedException Ginger\Core\Exception\InvalidArgumentException
     */
    public function testUnknownTypeThrowsException()
    {
        $resourceType = new ResourceType('unknown');
    }
}
