<?php

namespace Ginger\Core\Repository\Resource;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-10 at 23:59:24.
 */
class ResourceDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ResourceData
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ResourceData;
    }

    /**
     * @covers Ginger\Core\Repository\Resource\ResourceData::getResourceId
     */
    public function testGetResourceId()
    {
        $this->assertNull($this->object->getResourceId());
        
        $dataWithId = new ResourceData(new ResourceId('1234'));
        
        $this->assertEquals('1234', $dataWithId->getResourceId()->getValue());
    }

    /**
     * @covers Ginger\Core\Repository\Resource\ResourceData::setData
     * @covers Ginger\Core\Repository\Resource\ResourceData::getData
     */
    public function testSetGetData()
    {
        $this->object->setData(array('akey' => 'somevalue'));
        
        $this->assertEquals(array('akey' => 'somevalue'), $this->object->getData());
    }
}
