<?php

namespace Ginger\Core\Repository\Resource;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-10 at 23:55:49.
 */
class ResourceIdTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Ginger\Core\Repository\Resource\ResourceId::getValue
     */
    public function testGetValue()
    {
        $resourceId = new ResourceId('1234');
        
        $this->assertEquals('1234', $resourceId->getValue());
    }

    /**
     * @expectedException Ginger\Core\Exception\InvalidArgumentException
     */
    public function testExceptionOnWrongType()
    {
        $resourceId = new ResourceId(1.2);
    }
    
    /**
     * @expectedException Ginger\Core\Exception\InvalidArgumentException
     */
    public function testExceptionOnEmptyId()
    {
        $resourceId = new ResourceId('');
    }
}
