<?php

namespace Ginger\Core\Repository\Adapter;

use Zend\ServiceManager\ServiceManager;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-17 at 19:30:45.
 */
class MongoDbCrudAdapterFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var MongoDbCrudAdapterFactory
     */
    protected $object;
    
    /**
     *
     * @var \MongoClient
     */
    protected $mongoClient;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->mongoClient = new \MongoClient();
        
        $this->object = new MongoDbCrudAdapterFactory();
    }
    
    protected function tearDown()
    {
        $this->mongoClient->selectDB('gingerwfms-test')->drop();
    }

    /**
     * @covers Ginger\Core\Repository\Adapter\MongoDbCrudAdapterFactory::createService
     */
    public function testCreateService()
    {
        $serviceLocator = new ServiceManager();
        
        $serviceLocator->setService(
            'configuration', 
            array(
                'crud_adapter' => array(
                    'mongodb' => array(
                        'database' => 'gingerwfms-test'
                    )
                )
            )
        );
        
        $adapter = $this->object->createService($serviceLocator);
        
        $this->assertInstanceOf('Ginger\Core\Repository\Adapter\MongoDbCrudRepositoryAdapter', $adapter);
    }

}
